CREATE TABLE IF NOT EXISTS USERS
(
    ID    INTEGER           NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL CHARACTER VARYING NOT NULL,
    NAME  CHARACTER VARYING,

    CONSTRAINT PK_USER_ID PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS REQUESTS
(
    ID          INTEGER NOT NULL AUTO_INCREMENT,
    DESCRIPTION CHARACTER VARYING,
    REQUESTOR_ID   INTEGER,
    CREATED     TIMESTAMP,

    CONSTRAINT PK_REQUEST_ID PRIMARY KEY (ID),
    CONSTRAINT FK_REQUEST_USER FOREIGN KEY (REQUESTOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        CHARACTER VARYING,
    DESCRIPTION CHARACTER VARYING,
    AVAILABLE   BOOLEAN,
    OWNER       INTEGER,
    REQUEST     INTEGER,

    CONSTRAINT PK_ITEM_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_USER FOREIGN KEY (OWNER) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
--     CONSTRAINT FK_ITEM_REQUEST FOREIGN KEY (REQUEST) REFERENCES ITEM_REQUESTS (ID) ON DELETE SET NULL ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS BOOKING
(
    ID         INTEGER NOT NULL AUTO_INCREMENT,
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    ITEM_ID       INTEGER,
    BOOKER_ID     INTEGER,
    STATUS     CHARACTER VARYING,

    CONSTRAINT PK_BOOKING_ID PRIMARY KEY (ID),
    CONSTRAINT FK_BOOKING_USER FOREIGN KEY (BOOKER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FK_BOOKING_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
)

